# Generated by Django 3.1 on 2020-08-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_blog', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
    ]
